import { capabilityOf } from '../integrations.js';
import { integrationRows, pulledReceiver } from './integration-signals.js';
import type { ResolvedService, ResolvedSlo, ResolvedWorkspace } from '../model.js';
import {
  buildDashboard,
  q,
  type DashboardSpec,
  type PanelSpec,
  type RowSpec,
} from './dashboard-builder.js';
import { SLO_METRICS, sloSupported } from './slo.js';
import type { Artifact } from './types.js';

export interface DashboardContext {
  ws: ResolvedWorkspace;
  traces: boolean;
  serviceGraph: boolean;
  hostMetrics: boolean;
  containerMetrics: boolean;
}

export const DASHBOARD_UIDS = {
  overview: 'raion-overview',
  dependencies: 'raion-dependencies',
  logs: 'raion-logs',
  traces: 'raion-traces',
  infrastructure: 'raion-infrastructure',
  containers: 'raion-containers',
  stack: 'raion-stack-health',
  alerts: 'raion-alerts',
  slos: 'raion-slos',
} as const;

export function serviceDashboardUid(service: string): string {
  return `raion-svc-${service}`;
}

/** Calls an application makes to the collector itself are telemetry export, not dependencies. */
const NOT_TELEMETRY = 'server_address!="otel-collector"';

/** Filesystems that hold data (not virtual, in-memory or shared-folder mounts). */
export const REAL_FS = 'fstype!~"tmpfs|overlay|squashfs|nsfs|9p|fuse.*|rootfs|autofs|ramfs"';

const SIGNAL_SUFFIXES = ['spans', 'metric_points', 'log_records'];

/** Sum of several counters, each defaulting to 0 when it does not exist yet. */
function sumCounters(metrics: string[], fn: 'rate' | 'increase', range: string): string {
  return metrics.map((m) => `(sum(${fn}(${m}[${range}])) or vector(0))`).join(' + ');
}

const REFUSED = SIGNAL_SUFFIXES.flatMap((s) => [
  `otelcol_receiver_refused_${s}`,
  `otelcol_receiver_failed_${s}`,
]);
const EXPORT_FAILED = SIGNAL_SUFFIXES.map((s) => `otelcol_exporter_send_failed_${s}`);

const NAV_LINKS = [
  {
    type: 'dashboards',
    tags: ['raion'],
    asDropdown: true,
    title: 'Raion dashboards',
    includeVars: false,
    keepTime: true,
  },
];

function intro(content: string): PanelSpec {
  return { type: 'text', title: '', description: '', width: 24, height: 3, content };
}

// ----- per service -------------------------------------------------------------------------

function serviceDashboard(ctx: DashboardContext, svc: ResolvedService): DashboardSpec {
  const name = q(svc.name);
  const rows: RowSpec[] = [];
  const http = capabilityOf(svc.capabilities, 'http.server');
  const client = capabilityOf(svc.capabilities, 'http.client');

  rows.push({
    title: 'About',
    panels: [
      intro(
        `**${svc.name}**${svc.description ? ` — ${svc.description}` : ''}. Team: ${svc.team ?? 'not set'} · tier: ${svc.tier} · level ${svc.level}.\n\n` +
          'The **golden signals** below answer: how much traffic is there, how much of it fails, and how fast is it? ' +
          'Generated by Raion from the service definition; edit the workspace, not this dashboard.',
      ),
    ],
  });

  if (http) {
    const m = http.metrics.requestDuration;
    const sel = `service_name=${name}`;
    const status = m.labels.status;
    const route = m.labels.route;
    rows.push({
      title: 'Golden signals',
      panels: [
        {
          type: 'stat',
          title: 'Requests',
          description: 'Requests per second handled by the service (last 5 minutes).',
          datasource: 'prometheus',
          unit: 'reqps',
          width: 6,
          height: 5,
          targets: [{ refId: 'A', expr: `sum(rate(${m.name}_count{${sel}}[5m]))` }],
        },
        {
          type: 'stat',
          title: 'Error rate',
          description: 'Share of requests answered with a server error (HTTP 5xx), last 5 minutes.',
          datasource: 'prometheus',
          unit: 'percentunit',
          width: 6,
          height: 5,
          thresholds: [
            { color: 'green', value: null },
            { color: 'orange', value: 0.01 },
            { color: 'red', value: 0.05 },
          ],
          targets: [
            {
              refId: 'A',
              expr: `(sum(rate(${m.name}_count{${sel},${status}=~"5.."}[5m])) or vector(0)) / sum(rate(${m.name}_count{${sel}}[5m]))`,
            },
          ],
        },
        {
          type: 'stat',
          title: 'p95 latency',
          description: '95% of requests were faster than this (last 5 minutes).',
          datasource: 'prometheus',
          unit: 's',
          width: 6,
          height: 5,
          targets: [
            {
              refId: 'A',
              expr: `histogram_quantile(0.95, sum by (le) (rate(${m.name}_bucket{${sel}}[5m])))`,
            },
          ],
        },
        {
          type: 'stat',
          title: 'Instances',
          description: 'Running processes reporting metrics for this service.',
          datasource: 'prometheus',
          unit: 'short',
          width: 6,
          height: 5,
          targets: [
            {
              refId: 'A',
              expr: `count(count by (instance) (rate(${m.name}_count{${sel}}[5m]) > 0))`,
            },
          ],
        },
        {
          type: 'timeseries',
          title: 'Traffic by status class',
          description: 'Requests per second, split into 2xx, 3xx, 4xx and 5xx responses.',
          datasource: 'prometheus',
          unit: 'reqps',
          width: 12,
          stack: true,
          targets: [
            {
              refId: 'A',
              expr: `sum by (class) (label_replace(rate(${m.name}_count{${sel}}[$__rate_interval]), "class", "$1xx", "${status}", "([0-9]).."))`,
              legendFormat: '{{class}}',
            },
          ],
        },
        {
          type: 'timeseries',
          title: 'Error rate',
          description: 'Share of requests answered with HTTP 5xx.',
          datasource: 'prometheus',
          unit: 'percentunit',
          min: 0,
          width: 12,
          targets: [
            {
              refId: 'A',
              expr: `(sum(rate(${m.name}_count{${sel},${status}=~"5.."}[$__rate_interval])) or vector(0)) / sum(rate(${m.name}_count{${sel}}[$__rate_interval]))`,
              legendFormat: 'errors',
            },
          ],
        },
        {
          type: 'timeseries',
          title: 'Latency',
          description:
            'Response time percentiles: half of requests are faster than p50, 95% faster than p95, 99% faster than p99.',
          datasource: 'prometheus',
          unit: 's',
          width: 24,
          targets: ['0.5', '0.95', '0.99'].map((quantile, i) => ({
            refId: String.fromCharCode(65 + i),
            expr: `histogram_quantile(${quantile}, sum by (le) (rate(${m.name}_bucket{${sel}}[$__rate_interval])))`,
            legendFormat: `p${Number(quantile) * 100}`,
          })),
        },
      ],
    });
    if (route) {
      rows.push({
        title: 'By route',
        panels: [
          {
            type: 'timeseries',
            title: 'Requests by route',
            description: 'Which endpoints receive the traffic.',
            datasource: 'prometheus',
            unit: 'reqps',
            width: 12,
            targets: [
              {
                refId: 'A',
                expr: `sum by (${m.labels.method ?? 'le'}, ${route}) (rate(${m.name}_count{${sel},${route}!=""}[$__rate_interval]))`,
                legendFormat: m.labels.method
                  ? `{{${m.labels.method}}} {{${route}}}`
                  : `{{${route}}}`,
              },
            ],
          },
          {
            type: 'timeseries',
            title: 'p95 latency by route',
            description: 'Which endpoints are slow.',
            datasource: 'prometheus',
            unit: 's',
            width: 12,
            targets: [
              {
                refId: 'A',
                expr: `histogram_quantile(0.95, sum by (le, ${route}) (rate(${m.name}_bucket{${sel},${route}!=""}[$__rate_interval])))`,
                legendFormat: `{{${route}}}`,
              },
            ],
          },
        ],
      });
    }
  }

  rows.push(...integrationRows(svc));

  // Docker: the service's containers, from cAdvisor (infrastructure.containers).
  if (ctx.containerMetrics && svc.runtime.type === 'compose') {
    const sel = `container_label_com_docker_compose_service=${q(svc.runtime.composeService ?? svc.name)}`;
    rows.push({
      title: 'Containers',
      panels: [
        {
          type: 'timeseries',
          title: 'CPU',
          description: "CPU cores used by each of the service's containers.",
          datasource: 'prometheus',
          unit: 'short',
          width: 8,
          targets: [
            {
              refId: 'A',
              expr: `sum by (name) (rate(container_cpu_usage_seconds_total{${sel}}[$__rate_interval]))`,
              legendFormat: '{{name}}',
            },
          ],
        },
        {
          type: 'timeseries',
          title: 'Memory',
          description:
            'Working-set memory of each container, the figure the kernel uses before killing a container that exceeds its limit.',
          datasource: 'prometheus',
          unit: 'bytes',
          width: 8,
          targets: [
            {
              refId: 'A',
              expr: `sum by (name) (container_memory_working_set_bytes{${sel}})`,
              legendFormat: '{{name}}',
            },
          ],
        },
        {
          type: 'stat',
          title: 'Restarts (1 hour)',
          description:
            'How often the containers started in the last hour. More than once usually means crashes or out-of-memory kills.',
          datasource: 'prometheus',
          unit: 'short',
          width: 8,
          thresholds: [
            { color: 'green', value: null },
            { color: 'red', value: 1 },
          ],
          targets: [
            {
              refId: 'A',
              expr: `sum(changes(container_start_time_seconds{${sel}}[1h]))`,
            },
          ],
        },
      ],
    });
  }
  // The collector reads databases and proxies; they send no logs or traces of their own.
  const pulled = pulledReceiver(svc) !== undefined;

  const slos = deployedSlos(svc);
  if (slos.length > 0) {
    rows.push({
      title: 'Service level objectives',
      panels: slos.flatMap((slo) => sloPanels(svc, slo, true)),
    });
  }

  const depPanels: PanelSpec[] = [];
  if (client) {
    const m = client.metrics.requestDuration;
    const sel = `service_name=${name},${NOT_TELEMETRY}`;
    const hasDeps = svc.dependencies.length > 0;
    depPanels.push(
      {
        type: 'timeseries',
        title: 'Outgoing calls by destination',
        description: 'HTTP requests this service makes to other services and APIs.',
        datasource: 'prometheus',
        unit: 'reqps',
        width: 8,
        expect: hasDeps ? 'data' : 'optional',
        targets: [
          {
            refId: 'A',
            expr: `sum by (server_address) (rate(${m.name}_count{${sel}}[$__rate_interval]))`,
            legendFormat: '{{server_address}}',
          },
        ],
      },
      {
        type: 'timeseries',
        title: 'Outgoing call errors',
        description: 'Share of outgoing calls that failed with HTTP 5xx, per destination.',
        datasource: 'prometheus',
        unit: 'percentunit',
        width: 8,
        expect: 'optional',
        targets: [
          {
            refId: 'A',
            expr: `sum by (server_address) (rate(${m.name}_count{${sel},${m.labels.status}=~"5.."}[$__rate_interval])) / sum by (server_address) (rate(${m.name}_count{${sel}}[$__rate_interval]))`,
            legendFormat: '{{server_address}}',
          },
        ],
      },
      {
        type: 'timeseries',
        title: 'Outgoing call latency (p95)',
        description: 'How long calls to each destination take.',
        datasource: 'prometheus',
        unit: 's',
        width: 8,
        expect: hasDeps ? 'data' : 'optional',
        targets: [
          {
            refId: 'A',
            expr: `histogram_quantile(0.95, sum by (le, server_address) (rate(${m.name}_bucket{${sel}}[$__rate_interval])))`,
            legendFormat: '{{server_address}}',
          },
        ],
      },
    );
  }
  if (ctx.serviceGraph && svc.features.serviceGraph) {
    depPanels.push({
      type: 'timeseries',
      title: 'Called by',
      description:
        'Who sends requests to this service, from traces ("user" means callers that are not traced).',
      datasource: 'prometheus',
      unit: 'reqps',
      width: 24,
      expect: 'optional',
      targets: [
        {
          refId: 'A',
          expr: `sum by (client) (rate(traces_service_graph_request_total{server=${name}}[$__rate_interval]))`,
          legendFormat: '{{client}}',
        },
      ],
    });
  }
  if (depPanels.length > 0) rows.push({ title: 'Dependencies', panels: depPanels });

  if (capabilityOf(svc.capabilities, 'runtime.nodejs')) {
    const sel = `service_name=${name}`;
    rows.push({
      title: 'Node.js runtime (saturation)',
      panels: [
        {
          type: 'timeseries',
          title: 'Event loop delay (p99)',
          description:
            'How long work waits for the event loop. Rising values mean the process is overloaded.',
          datasource: 'prometheus',
          unit: 's',
          width: 8,
          targets: [
            {
              refId: 'A',
              expr: `max by (instance) (nodejs_eventloop_delay_p99_seconds{${sel}})`,
              legendFormat: '{{instance}}',
            },
          ],
        },
        {
          type: 'timeseries',
          title: 'Event loop utilization',
          description: 'Share of time the event loop is busy. Close to 100% means saturated.',
          datasource: 'prometheus',
          unit: 'percentunit',
          min: 0,
          max: 1,
          width: 8,
          targets: [
            {
              refId: 'A',
              expr: `max by (instance) (nodejs_eventloop_utilization_ratio{${sel}})`,
              legendFormat: '{{instance}}',
            },
          ],
        },
        {
          type: 'timeseries',
          title: 'Heap used',
          description: 'JavaScript heap memory in use. Steady growth may indicate a memory leak.',
          datasource: 'prometheus',
          unit: 'bytes',
          width: 8,
          targets: [
            {
              refId: 'A',
              expr: `sum by (instance) (v8js_memory_heap_used_bytes{${sel}})`,
              legendFormat: '{{instance}}',
            },
          ],
        },
      ],
    });
  }

  if ((!pulled || svc.containerLogs) && svc.signals.logs && svc.features.logs) {
    const stream = `{service_name=${name}}`;
    rows.push({
      title: 'Logs',
      panels: [
        {
          type: 'timeseries',
          title: 'Log volume by level',
          description: 'Log lines per minute, by severity.',
          datasource: 'loki',
          unit: 'short',
          width: 24,
          height: 6,
          stack: true,
          targets: [
            {
              refId: 'A',
              expr: `sum by (detected_level) (count_over_time(${stream} [1m]))`,
              legendFormat: '{{detected_level}}',
            },
          ],
        },
        {
          type: 'logs',
          title: 'Errors and warnings',
          description: 'Recent error and warning logs. Lines with a trace ID link to the trace.',
          datasource: 'loki',
          width: 12,
          height: 10,
          expect: 'optional',
          targets: [
            { refId: 'A', expr: `${stream} | detected_level=~"error|fatal|critical|warn|warning"` },
          ],
        },
        {
          type: 'logs',
          title: 'Recent logs',
          description: 'All recent log lines of the service.',
          datasource: 'loki',
          width: 12,
          height: 10,
          targets: [{ refId: 'A', expr: stream }],
        },
      ],
    });
  }

  if (!pulled && ctx.traces && svc.features.traces && svc.signals.traces) {
    rows.push({
      title: 'Traces',
      panels: [
        {
          type: 'table',
          title: 'Slow requests (over 500 ms)',
          description:
            'Recent traces of requests that took longer than 500 ms. Click a trace ID to open it.',
          datasource: 'tempo',
          width: 12,
          height: 9,
          expect: 'optional',
          targets: [
            {
              refId: 'A',
              queryType: 'traceql',
              query: `{resource.service.name=${name} && kind=server && duration > 500ms}`,
              limit: 20,
            },
          ],
        },
        {
          type: 'table',
          title: 'Failed requests',
          description: 'Recent traces that ended in an error.',
          datasource: 'tempo',
          width: 12,
          height: 9,
          expect: 'optional',
          targets: [
            {
              refId: 'A',
              queryType: 'traceql',
              query: `{resource.service.name=${name} && status=error}`,
              limit: 20,
            },
          ],
        },
        {
          type: 'table',
          title: 'Recent requests',
          description: 'The most recent traces of this service.',
          datasource: 'tempo',
          width: 24,
          height: 9,
          targets: [
            {
              refId: 'A',
              queryType: 'traceql',
              query: `{resource.service.name=${name} && kind=server}`,
              limit: 20,
            },
          ],
        },
      ],
    });
  }

  return {
    uid: serviceDashboardUid(svc.name),
    title: `Service · ${svc.name}`,
    description: `Golden signals, dependencies, logs and traces of ${svc.name}. Generated by Raion.`,
    tags: ['raion', 'raion-service', ...(svc.team ? [`team-${svc.team}`] : [])],
    rows,
    links: NAV_LINKS,
  };
}

// ----- workspace-wide -------------------------------------------------------------------------

function httpServices(ctx: DashboardContext): ResolvedService[] {
  return ctx.ws.services.filter((s) => capabilityOf(s.capabilities, 'http.server'));
}

function overviewDashboard(ctx: DashboardContext): DashboardSpec {
  const services = httpServices(ctx);
  const metric = services
    .map((s) => capabilityOf(s.capabilities, 'http.server')!.metrics.requestDuration)
    .find(Boolean);
  const rows: RowSpec[] = [
    {
      title: 'About',
      panels: [
        intro(
          `**${ctx.ws.name}** · ${ctx.ws.environment} · level ${ctx.ws.level}. One line per service: how much traffic, how much fails, how fast. ` +
            'Open a service from the **Raion dashboards** menu for details.',
        ),
      ],
    },
  ];
  if (metric && services.length > 0) {
    const sel = `service_name=~${q(services.map((s) => s.name).join('|'))}`;
    rows.push({
      title: 'Services',
      panels: [
        {
          type: 'timeseries',
          title: 'Requests per service',
          description: 'Requests per second handled by each service.',
          datasource: 'prometheus',
          unit: 'reqps',
          width: 8,
          targets: [
            {
              refId: 'A',
              expr: `sum by (service_name) (rate(${metric.name}_count{${sel}}[$__rate_interval]))`,
              legendFormat: '{{service_name}}',
            },
          ],
        },
        {
          type: 'timeseries',
          title: 'Error rate per service',
          description: 'Share of requests answered with HTTP 5xx.',
          datasource: 'prometheus',
          unit: 'percentunit',
          min: 0,
          width: 8,
          targets: [
            {
              refId: 'A',
              expr: `sum by (service_name) (rate(${metric.name}_count{${sel},${metric.labels.status}=~"5.."}[$__rate_interval])) / sum by (service_name) (rate(${metric.name}_count{${sel}}[$__rate_interval]))`,
              legendFormat: '{{service_name}}',
            },
          ],
          expect: 'optional',
        },
        {
          type: 'timeseries',
          title: 'p95 latency per service',
          description: '95% of requests were faster than this.',
          datasource: 'prometheus',
          unit: 's',
          width: 8,
          targets: [
            {
              refId: 'A',
              expr: `histogram_quantile(0.95, sum by (le, service_name) (rate(${metric.name}_bucket{${sel}}[$__rate_interval])))`,
              legendFormat: '{{service_name}}',
            },
          ],
        },
      ],
    });
  }
  rows.push({
    title: 'Observability stack',
    panels: [
      {
        type: 'stat',
        title: 'Monitored components up',
        description:
          'Share of the stack components Prometheus can reach. Below 100% means part of the monitoring is broken.',
        datasource: 'prometheus',
        unit: 'percentunit',
        width: 12,
        height: 5,
        thresholds: [
          { color: 'red', value: null },
          { color: 'green', value: 1 },
        ],
        targets: [{ refId: 'A', expr: 'avg(up)' }],
      },
      {
        type: 'stat',
        title: 'Telemetry refused or failed',
        description:
          'Items the collector could not accept or deliver in the last 15 minutes. Should be 0.',
        datasource: 'prometheus',
        unit: 'short',
        width: 12,
        height: 5,
        thresholds: [
          { color: 'green', value: null },
          { color: 'red', value: 1 },
        ],
        targets: [
          {
            refId: 'A',
            expr: sumCounters([...REFUSED, ...EXPORT_FAILED], 'increase', '15m'),
          },
        ],
      },
    ],
  });
  return {
    uid: DASHBOARD_UIDS.overview,
    title: 'Raion · Overview',
    description: 'All services and the health of the observability stack at a glance.',
    tags: ['raion'],
    rows,
    links: NAV_LINKS,
  };
}

function dependenciesDashboard(ctx: DashboardContext): DashboardSpec {
  return {
    uid: DASHBOARD_UIDS.dependencies,
    title: 'Raion · Dependencies',
    description: 'Which services call which, derived from traces.',
    tags: ['raion'],
    links: NAV_LINKS,
    rows: [
      {
        title: 'Service map',
        panels: [
          intro(
            'Every arrow is a real call seen in traces in the selected time range, with its request rate and error rate. ' +
              '"user" stands for callers that are not traced (browsers, load balancers, scripts). Declared dependencies in your workspace: ' +
              (ctx.ws.services
                .flatMap((s) =>
                  s.dependencies.map(
                    (d) => `${s.name} → ${'service' in d ? d.service : d.external.name}`,
                  ),
                )
                .join(', ') || 'none'),
          ),
          {
            type: 'nodeGraph',
            title: 'Service map',
            description: 'Services as nodes, calls as edges.',
            datasource: 'tempo',
            width: 24,
            height: 14,
            targets: [{ refId: 'A', queryType: 'serviceMap', serviceMapQuery: '{}' }],
          },
          {
            type: 'timeseries',
            title: 'Calls between services',
            description: 'Requests per second for each caller → callee pair.',
            datasource: 'prometheus',
            unit: 'reqps',
            width: 12,
            targets: [
              {
                refId: 'A',
                expr: 'sum by (client, server) (rate(traces_service_graph_request_total[$__rate_interval]))',
                legendFormat: '{{client}} → {{server}}',
              },
            ],
          },
          {
            type: 'timeseries',
            title: 'Failed calls between services',
            description: 'Share of calls between two services that failed.',
            datasource: 'prometheus',
            unit: 'percentunit',
            width: 12,
            expect: 'optional',
            targets: [
              {
                refId: 'A',
                expr: 'sum by (client, server) (rate(traces_service_graph_request_failed_total[$__rate_interval])) / sum by (client, server) (rate(traces_service_graph_request_total[$__rate_interval]))',
                legendFormat: '{{client}} → {{server}}',
              },
            ],
          },
        ],
      },
    ],
  };
}

function logsDashboard(ctx: DashboardContext): DashboardSpec {
  const names = ctx.ws.services.filter((s) => s.signals.logs && s.features.logs).map((s) => s.name);
  const stream =
    names.length > 0 ? `{service_name=~${q(names.join('|'))}}` : '{service_name=~".+"}';
  return {
    uid: DASHBOARD_UIDS.logs,
    title: 'Raion · Logs',
    description: 'Logs of every service, with errors first.',
    tags: ['raion'],
    links: NAV_LINKS,
    rows: [
      {
        title: 'Logs',
        panels: [
          {
            type: 'timeseries',
            title: 'Log volume by service',
            description: 'Log lines per minute.',
            datasource: 'loki',
            unit: 'short',
            width: 12,
            height: 7,
            expect: names.length > 0 ? 'data' : 'optional',
            targets: [
              {
                refId: 'A',
                expr: `sum by (service_name) (count_over_time(${stream} [1m]))`,
                legendFormat: '{{service_name}}',
              },
            ],
          },
          {
            type: 'timeseries',
            title: 'Errors by service',
            description: 'Error log lines per minute.',
            datasource: 'loki',
            unit: 'short',
            width: 12,
            height: 7,
            expect: 'optional',
            targets: [
              {
                refId: 'A',
                expr: `sum by (service_name) (count_over_time(${stream} | detected_level=~"error|fatal|critical" [1m]))`,
                legendFormat: '{{service_name}}',
              },
            ],
          },
          {
            type: 'logs',
            title: 'Errors',
            description: 'Recent error logs from all services.',
            datasource: 'loki',
            width: 24,
            height: 12,
            expect: 'optional',
            targets: [{ refId: 'A', expr: `${stream} | detected_level=~"error|fatal|critical"` }],
          },
        ],
      },
    ],
  };
}

function tracesDashboard(): DashboardSpec {
  return {
    uid: DASHBOARD_UIDS.traces,
    title: 'Raion · Traces',
    description: 'Slow and failed requests across all services.',
    tags: ['raion'],
    links: NAV_LINKS,
    rows: [
      {
        title: 'Traces',
        panels: [
          {
            type: 'table',
            title: 'Failed requests',
            description: 'Recent traces that ended in an error, in any service.',
            datasource: 'tempo',
            width: 12,
            height: 12,
            expect: 'optional',
            targets: [{ refId: 'A', queryType: 'traceql', query: '{status=error}', limit: 25 }],
          },
          {
            type: 'table',
            title: 'Slowest requests (over 1 s)',
            description: 'Recent traces of requests that took longer than one second.',
            datasource: 'tempo',
            width: 12,
            height: 12,
            expect: 'optional',
            targets: [
              {
                refId: 'A',
                queryType: 'traceql',
                query: '{kind=server && duration > 1s}',
                limit: 25,
              },
            ],
          },
          {
            type: 'table',
            title: 'Recent requests',
            description: 'The most recent traces.',
            datasource: 'tempo',
            width: 24,
            height: 10,
            targets: [{ refId: 'A', queryType: 'traceql', query: '{kind=server}', limit: 25 }],
          },
        ],
      },
    ],
  };
}

function infrastructureDashboard(): DashboardSpec {
  return {
    uid: DASHBOARD_UIDS.infrastructure,
    title: 'Raion · Infrastructure',
    description: 'CPU, memory, disk and network of the host running the stack (node_exporter).',
    tags: ['raion'],
    links: NAV_LINKS,
    rows: [
      {
        title: 'Host',
        panels: [
          intro(
            "Resources of the machine running the observability stack and your Compose services. On Docker Desktop this is Docker's Linux VM. " +
              "Network panels currently show node_exporter's own container interface, not the host's (see the Raion docs).",
          ),
          {
            type: 'stat',
            title: 'CPU busy',
            description: 'Share of CPU time spent working (not idle), averaged over all cores.',
            datasource: 'prometheus',
            unit: 'percentunit',
            width: 6,
            height: 5,
            targets: [
              { refId: 'A', expr: '1 - avg(rate(node_cpu_seconds_total{mode="idle"}[5m]))' },
            ],
          },
          {
            type: 'stat',
            title: 'Memory used',
            description: 'Share of memory in use (excluding reclaimable cache).',
            datasource: 'prometheus',
            unit: 'percentunit',
            width: 6,
            height: 5,
            targets: [
              {
                refId: 'A',
                expr: '1 - sum(node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)',
              },
            ],
          },
          {
            type: 'stat',
            title: 'Fullest disk',
            description:
              'Use of the fullest real filesystem (ignores in-memory and virtual mounts).',
            datasource: 'prometheus',
            unit: 'percentunit',
            width: 6,
            height: 5,
            thresholds: [
              { color: 'green', value: null },
              { color: 'orange', value: 0.8 },
              { color: 'red', value: 0.9 },
            ],
            targets: [
              {
                refId: 'A',
                expr: `max(1 - node_filesystem_avail_bytes{${REAL_FS}} / node_filesystem_size_bytes{${REAL_FS}})`,
              },
            ],
          },
          {
            type: 'stat',
            title: 'Load (1 min) per core',
            description: 'Runnable processes per CPU core. Above 1 means work is queuing.',
            datasource: 'prometheus',
            unit: 'short',
            width: 6,
            height: 5,
            targets: [
              {
                refId: 'A',
                expr: 'max(node_load1) / count(count by (cpu) (node_cpu_seconds_total))',
              },
            ],
          },
          {
            type: 'timeseries',
            title: 'CPU by mode',
            description:
              'Where CPU time goes: user programs, the kernel, waiting for disk (iowait)…',
            datasource: 'prometheus',
            unit: 'percentunit',
            width: 12,
            stack: true,
            targets: [
              {
                refId: 'A',
                expr: 'avg by (mode) (rate(node_cpu_seconds_total{mode!="idle"}[$__rate_interval]))',
                legendFormat: '{{mode}}',
              },
            ],
          },
          {
            type: 'timeseries',
            title: 'Memory',
            description: 'Memory in use and available.',
            datasource: 'prometheus',
            unit: 'bytes',
            width: 12,
            targets: [
              {
                refId: 'A',
                expr: 'sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)',
                legendFormat: 'used',
              },
              {
                refId: 'B',
                expr: 'sum(node_memory_MemAvailable_bytes)',
                legendFormat: 'available',
              },
            ],
          },
          {
            type: 'timeseries',
            title: 'Disk throughput',
            description: 'Bytes read from and written to disk.',
            datasource: 'prometheus',
            unit: 'Bps',
            width: 12,
            targets: [
              {
                refId: 'A',
                expr: 'sum(rate(node_disk_read_bytes_total[$__rate_interval]))',
                legendFormat: 'read',
              },
              {
                refId: 'B',
                expr: 'sum(rate(node_disk_written_bytes_total[$__rate_interval]))',
                legendFormat: 'written',
              },
            ],
          },
          {
            type: 'timeseries',
            title: 'Filesystem usage',
            description: 'Share used, per mounted filesystem.',
            datasource: 'prometheus',
            unit: 'percentunit',
            width: 12,
            targets: [
              {
                refId: 'A',
                expr: `max by (device) (1 - node_filesystem_avail_bytes{${REAL_FS}} / node_filesystem_size_bytes{${REAL_FS}})`,
                legendFormat: '{{device}}',
              },
            ],
          },
        ],
      },
    ],
  };
}

function containersDashboard(): DashboardSpec {
  const sel = 'name!=""';
  return {
    uid: DASHBOARD_UIDS.containers,
    title: 'Raion · Containers',
    description: 'CPU and memory per container (cAdvisor).',
    tags: ['raion'],
    links: NAV_LINKS,
    rows: [
      {
        title: 'Containers',
        panels: [
          {
            type: 'timeseries',
            title: 'CPU per container',
            description: 'CPU cores used by each container.',
            datasource: 'prometheus',
            unit: 'short',
            width: 12,
            targets: [
              {
                refId: 'A',
                expr: `sum by (name) (rate(container_cpu_usage_seconds_total{${sel}}[$__rate_interval]))`,
                legendFormat: '{{name}}',
              },
            ],
          },
          {
            type: 'timeseries',
            title: 'Memory per container',
            description: 'Working-set memory of each container.',
            datasource: 'prometheus',
            unit: 'bytes',
            width: 12,
            targets: [
              {
                refId: 'A',
                expr: `sum by (name) (container_memory_working_set_bytes{${sel}})`,
                legendFormat: '{{name}}',
              },
            ],
          },
        ],
      },
    ],
  };
}

function stackHealthDashboard(ctx: DashboardContext): DashboardSpec {
  const signals = [
    { label: 'spans', unit: 'spans', on: ctx.traces },
    { label: 'metric_points', unit: 'metric points', on: true },
    { label: 'log_records', unit: 'log records', on: true },
  ].filter((s) => s.on);
  const panels: PanelSpec[] = [
    intro(
      'Is the monitoring itself working? Every component should be **up**, the collector should accept everything it receives and deliver everything it accepts, and queues should stay far below capacity.',
    ),
    {
      type: 'bargauge',
      title: 'Components up',
      description: '1 when Prometheus can scrape the component, 0 when it cannot.',
      datasource: 'prometheus',
      unit: 'short',
      min: 0,
      max: 1,
      width: 8,
      height: 9,
      thresholds: [
        { color: 'red', value: null },
        { color: 'green', value: 1 },
      ],
      targets: [{ refId: 'A', expr: 'max by (job) (up)', legendFormat: '{{job}}', instant: true }],
    },
    {
      type: 'timeseries',
      title: 'Telemetry received by the collector',
      description: 'Items per second accepted from applications, per signal.',
      datasource: 'prometheus',
      unit: 'short',
      width: 16,
      height: 9,
      targets: signals.map((s, i) => ({
        refId: String.fromCharCode(65 + i),
        expr: `sum(rate(otelcol_receiver_accepted_${s.label}[$__rate_interval]))`,
        legendFormat: s.unit,
      })),
    },
    {
      type: 'timeseries',
      title: 'Refused or failed telemetry',
      description:
        'Items the collector refused (overloaded) or could not deliver to storage. Should stay at 0.',
      datasource: 'prometheus',
      unit: 'short',
      width: 12,
      targets: [
        {
          refId: 'A',
          expr: sumCounters(REFUSED, 'rate', '$__rate_interval'),
          legendFormat: 'refused by the collector',
        },
        {
          refId: 'B',
          expr: sumCounters(EXPORT_FAILED, 'rate', '$__rate_interval'),
          legendFormat: 'not delivered to storage',
        },
      ],
    },
    {
      type: 'timeseries',
      title: 'Export queue usage',
      description:
        "How full the collector's outgoing queues are. Near 100% means storage cannot keep up.",
      datasource: 'prometheus',
      unit: 'percentunit',
      min: 0,
      max: 1,
      width: 12,
      targets: [
        {
          refId: 'A',
          expr: 'max by (exporter) (otelcol_exporter_queue_size / otelcol_exporter_queue_capacity)',
          legendFormat: '{{exporter}}',
        },
      ],
    },
    {
      type: 'timeseries',
      title: 'Metric series stored',
      description:
        'Active time series in Prometheus. Sudden jumps usually mean a label with too many values (high cardinality).',
      datasource: 'prometheus',
      unit: 'short',
      width: 8,
      targets: [{ refId: 'A', expr: 'prometheus_tsdb_head_series', legendFormat: 'series' }],
    },
    {
      type: 'timeseries',
      title: 'Log lines stored',
      description: 'Log lines per second received by Loki.',
      datasource: 'prometheus',
      unit: 'short',
      width: 8,
      targets: [
        {
          refId: 'A',
          expr: 'sum(rate(loki_distributor_lines_received_total[$__rate_interval]))',
          legendFormat: 'lines',
        },
      ],
    },
  ];
  if (ctx.traces) {
    panels.push({
      type: 'timeseries',
      title: 'Spans stored',
      description: 'Spans per second received by Tempo.',
      datasource: 'prometheus',
      unit: 'short',
      width: 8,
      targets: [
        {
          refId: 'A',
          expr: 'sum(rate(tempo_distributor_spans_received_total[$__rate_interval]))',
          legendFormat: 'spans',
        },
      ],
    });
  }
  panels.push(
    {
      type: 'timeseries',
      title: 'Rule evaluation failures',
      description: 'Recording and alerting rules Prometheus failed to evaluate. Should stay at 0.',
      datasource: 'prometheus',
      unit: 'short',
      width: 12,
      targets: [
        {
          refId: 'A',
          expr: 'sum(rate(prometheus_rule_evaluation_failures_total[$__rate_interval])) or vector(0)',
          legendFormat: 'failures',
        },
      ],
    },
    {
      type: 'timeseries',
      title: 'Failed alert notifications',
      description: 'Notifications Alertmanager could not deliver. Should stay at 0.',
      datasource: 'prometheus',
      unit: 'short',
      width: 12,
      targets: [
        {
          refId: 'A',
          expr: 'sum(rate(alertmanager_notifications_failed_total[$__rate_interval])) or vector(0)',
          legendFormat: 'failed',
        },
      ],
    },
  );
  return {
    uid: DASHBOARD_UIDS.stack,
    title: 'Raion · Observability stack health',
    description: 'Is the monitoring itself working? Collector, storage and alerting health.',
    tags: ['raion'],
    links: NAV_LINKS,
    rows: [{ title: 'Pipeline', panels }],
  };
}

function alertsDashboard(): DashboardSpec {
  const firing = 'ALERTS{alertstate="firing", alertname!="Watchdog"}';
  return {
    uid: DASHBOARD_UIDS.alerts,
    title: 'Raion · Alerts',
    description: 'What is firing, and whether alerts are evaluated and delivered.',
    tags: ['raion'],
    links: NAV_LINKS,
    rows: [
      {
        title: 'Alerts',
        panels: [
          intro(
            'Alerts are evaluated by Prometheus and routed by Alertmanager. Every alert is also in the **Raion inbox** (Alerts page in Raion), whatever its notification route. ' +
              'The *Alerting pipeline* tile turns red when the always-firing Watchdog alert stops arriving, which means alerts are not being delivered.',
          ),
          {
            type: 'stat',
            title: 'Alerting pipeline',
            description:
              '1 when the Watchdog alert is firing as it should (rules are evaluated), 0 when alerting is broken.',
            datasource: 'prometheus',
            unit: 'short',
            width: 6,
            height: 5,
            thresholds: [
              { color: 'red', value: null },
              { color: 'green', value: 1 },
            ],
            targets: [
              {
                refId: 'A',
                expr: 'count(ALERTS{alertname="Watchdog", alertstate="firing"}) or vector(0)',
              },
            ],
          },
          {
            type: 'stat',
            title: 'Firing alerts',
            description: 'Alerts firing right now (excluding the Watchdog).',
            datasource: 'prometheus',
            unit: 'short',
            width: 6,
            height: 5,
            thresholds: [
              { color: 'green', value: null },
              { color: 'orange', value: 1 },
            ],
            targets: [{ refId: 'A', expr: `count(${firing}) or vector(0)` }],
          },
          {
            type: 'stat',
            title: 'Failed notifications (1 h)',
            description:
              'Notifications Alertmanager could not deliver in the last hour. Should be 0.',
            datasource: 'prometheus',
            unit: 'short',
            width: 12,
            height: 5,
            thresholds: [
              { color: 'green', value: null },
              { color: 'red', value: 1 },
            ],
            targets: [
              {
                refId: 'A',
                expr: 'sum(increase(alertmanager_notifications_failed_total[1h])) or vector(0)',
              },
            ],
          },
          {
            type: 'table',
            title: 'Firing now',
            description: 'Each firing alert with its labels.',
            datasource: 'prometheus',
            width: 24,
            height: 8,
            expect: 'optional',
            targets: [{ refId: 'A', expr: firing, instant: true }],
          },
          {
            type: 'timeseries',
            title: 'Firing alerts by severity',
            description: 'How many alerts were firing over time.',
            datasource: 'prometheus',
            unit: 'short',
            width: 12,
            stack: true,
            expect: 'optional',
            targets: [
              { refId: 'A', expr: `count by (severity) (${firing})`, legendFormat: '{{severity}}' },
            ],
          },
          {
            type: 'timeseries',
            title: 'Notifications sent and failed',
            description: 'Notifications per minute by channel (email, Slack, webhook).',
            datasource: 'prometheus',
            unit: 'short',
            width: 12,
            targets: [
              {
                refId: 'A',
                expr: 'sum by (integration) (increase(alertmanager_notifications_total[5m]))',
                legendFormat: 'sent · {{integration}}',
              },
              {
                refId: 'B',
                expr: 'sum by (integration) (increase(alertmanager_notifications_failed_total[5m]))',
                legendFormat: 'failed · {{integration}}',
              },
            ],
          },
        ],
      },
    ],
  };
}

// ----- SLOs ---------------------------------------------------------------------------------

function deployedSlos(svc: ResolvedService) {
  return svc.features.slos && svc.signals.metrics
    ? svc.slos.filter((slo) => sloSupported(svc, slo))
    : [];
}

function sloPanels(svc: ResolvedService, slo: ResolvedSlo, compact: boolean): PanelSpec[] {
  const sel = `service_name=${q(svc.name)},slo=${q(slo.name)}`;
  const objective = Number((slo.target / 100).toPrecision(10));
  const sloLabel = `${slo.name} (${slo.target}% over ${slo.window})`;
  const panels: PanelSpec[] = [
    {
      type: 'stat',
      title: compact ? `${slo.name}: SLI` : 'SLI',
      description: `Share of good events over the last ${slo.window}. The objective is ${slo.target}%.`,
      datasource: 'prometheus',
      unit: 'percentunit',
      width: compact ? 6 : 6,
      height: 5,
      thresholds: [
        { color: 'red', value: null },
        { color: 'green', value: objective },
      ],
      targets: [{ refId: 'A', expr: `${SLO_METRICS.sli}{${sel}}` }],
    },
    {
      type: 'stat',
      title: compact ? `${slo.name}: error budget left` : 'Error budget left',
      description: `How much of the allowed ${(100 - slo.target).toFixed(3).replace(/\.?0+$/, '')}% of failures over ${slo.window} is still unused. Below 0 the objective is missed.`,
      datasource: 'prometheus',
      unit: 'percentunit',
      width: 6,
      height: 5,
      thresholds: [
        { color: 'red', value: null },
        { color: 'orange', value: 0 },
        { color: 'green', value: 0.25 },
      ],
      targets: [{ refId: 'A', expr: `${SLO_METRICS.budgetRemaining}{${sel}}` }],
    },
  ];
  if (compact) return panels;
  panels.push(
    {
      type: 'stat',
      title: 'Burn rate (1 h)',
      description:
        'How fast the error budget is being used, as a multiple of the sustainable pace. Above 1 the budget runs out before the window ends.',
      datasource: 'prometheus',
      unit: 'short',
      width: 6,
      height: 5,
      thresholds: [
        { color: 'green', value: null },
        { color: 'orange', value: 1 },
        { color: 'red', value: 6 },
      ],
      targets: [
        { refId: 'A', expr: `${SLO_METRICS.errorRatio('1h')}{${sel}} / ${slo.errorBudgetRatio}` },
      ],
    },
    {
      type: 'stat',
      title: 'Objective',
      description: slo.description ?? `${slo.target}% of events must be good over ${slo.window}.`,
      datasource: 'prometheus',
      unit: 'percentunit',
      width: 6,
      height: 5,
      targets: [{ refId: 'A', expr: `${SLO_METRICS.objective}{${sel}}` }],
    },
    {
      type: 'timeseries',
      title: 'Error budget left over time',
      description:
        'A falling line means failures are using the budget; a flat line means no failures.',
      datasource: 'prometheus',
      unit: 'percentunit',
      width: 12,
      targets: [
        { refId: 'A', expr: `${SLO_METRICS.budgetRemaining}{${sel}}`, legendFormat: sloLabel },
      ],
    },
    {
      type: 'timeseries',
      title: 'Burn rate',
      description:
        'Budget use as a multiple of the sustainable pace, over short and long windows. Raion pages when both a long and a short window burn fast.',
      datasource: 'prometheus',
      unit: 'short',
      width: 12,
      targets: (['5m', '1h', '6h', '1d'] as const).map((w, i) => ({
        refId: String.fromCharCode(65 + i),
        expr: `${SLO_METRICS.errorRatio(w)}{${sel}} / ${slo.errorBudgetRatio}`,
        legendFormat: w,
      })),
    },
  );
  return panels;
}

function slosDashboard(ctx: DashboardContext): DashboardSpec {
  const rows: RowSpec[] = [
    {
      title: 'About',
      panels: [
        intro(
          'A **service level objective (SLO)** says how reliable a service must be, from its users\' point of view, e.g. "99.9% of requests succeed over 30 days". ' +
            'The **error budget** is the failure that is allowed (here 0.1%): spend it on releases and experiments, protect it when it runs low. ' +
            "The **burn rate** says how fast it is being spent: 1 means exactly on budget, 14 means a month's budget is gone in about two days.",
        ),
        {
          type: 'bargauge',
          title: 'Error budget left, per SLO',
          description: 'Every SLO at a glance. Red: the objective is missed over its window.',
          datasource: 'prometheus',
          unit: 'percentunit',
          width: 24,
          height: Math.max(
            4,
            2 + ctx.ws.services.reduce((n, svc) => n + deployedSlos(svc).length, 0),
          ),
          thresholds: [
            { color: 'red', value: null },
            { color: 'orange', value: 0 },
            { color: 'green', value: 0.25 },
          ],
          targets: [
            {
              refId: 'A',
              expr: SLO_METRICS.budgetRemaining,
              legendFormat: '{{service_name}} · {{slo}}',
              instant: true,
            },
          ],
        },
      ],
    },
  ];
  for (const svc of ctx.ws.services) {
    for (const slo of deployedSlos(svc)) {
      rows.push({
        title: `${svc.name} · ${slo.name} — ${slo.target}% over ${slo.window}`,
        panels: sloPanels(svc, slo, false),
      });
    }
  }
  return {
    uid: DASHBOARD_UIDS.slos,
    title: 'Raion · SLOs',
    description: 'Service level objectives, error budgets and burn rates.',
    tags: ['raion'],
    links: NAV_LINKS,
    rows,
  };
}

export interface GeneratedDashboard {
  uid: string;
  title: string;
  /** Service the dashboard belongs to, if any. */
  service?: string;
  json: Record<string, unknown>;
}

/** All dashboards for a workspace, derived from services, their capabilities and the deployed components. */
export function generateDashboards(ctx: DashboardContext): GeneratedDashboard[] {
  const specs: { spec: DashboardSpec; service?: string }[] = [
    { spec: overviewDashboard(ctx) },
    ...ctx.ws.services.map((svc) => ({ spec: serviceDashboard(ctx, svc), service: svc.name })),
    { spec: logsDashboard(ctx) },
    ...(ctx.traces ? [{ spec: tracesDashboard() }] : []),
    ...(ctx.serviceGraph ? [{ spec: dependenciesDashboard(ctx) }] : []),
    ...(ctx.hostMetrics ? [{ spec: infrastructureDashboard() }] : []),
    ...(ctx.containerMetrics ? [{ spec: containersDashboard() }] : []),
    ...(ctx.ws.services.some((svc) => deployedSlos(svc).length > 0)
      ? [{ spec: slosDashboard(ctx) }]
      : []),
    { spec: alertsDashboard() },
    { spec: stackHealthDashboard(ctx) },
  ];
  return specs.map(({ spec, service }) => ({
    uid: spec.uid,
    title: spec.title,
    ...(service ? { service } : {}),
    json: buildDashboard(spec),
  }));
}

export function dashboardArtifacts(dashboards: GeneratedDashboard[]): Artifact[] {
  return dashboards.map((d) => ({
    path: `grafana/provisioning/dashboards/raion/${d.uid}.json`,
    component: 'grafana',
    description: `Grafana dashboard: ${d.title}`,
    content: `${JSON.stringify(d.json, null, 2)}\n`,
    live: true,
  }));
}
