import { stringify } from 'yaml';

/** Serializes generated configuration with a header that explains where it came from. */
export function toYaml(value: unknown, header: string): string {
  const body = stringify(value, { lineWidth: 0, aliasDuplicateObjects: false });
  return `${header
    .trim()
    .split('\n')
    .map((line) => `# ${line}`.trimEnd())
    .join('\n')}\n${body}`;
}

export const GENERATED_HEADER = (what: string) =>
  `${what}
Generated by Raion. Do not edit: changes are overwritten on the next "raion apply".
To change it, edit your workspace files and run "raion plan".`;
