import { createHash } from 'node:crypto';
import { parse } from 'yaml';

/**
 * Drift: the running stack no longer matches the release Raion deployed. Workspace changes not
 * yet applied are not drift; "raion plan" shows those. Drift is what changed behind Raion's
 * back: hand-edited generated files, containers stopped, removed, added or replaced.
 */
export type DriftKind =
  | 'file-modified'
  | 'file-missing'
  | 'file-extra'
  | 'component-missing'
  | 'component-stopped'
  | 'component-extra'
  | 'image-changed';

export interface DriftItem {
  kind: DriftKind;
  /** File path (relative to the runtime directory) or component name. */
  subject: string;
  detail: string;
}

export interface DriftReport {
  /** The release the running stack is compared with; absent when nothing is deployed. */
  release?: string;
  items: DriftItem[];
}

export interface RunningContainer {
  service: string;
  state: string;
  image?: string;
}

const sha256 = (text: string) => createHash('sha256').update(text).digest('hex');

/** Compares the deployed release with the runtime directory and the containers. Pure. */
export function compareRuntime(input: {
  release: string;
  /** The release's files, as written at deployment. */
  expected: { path: string; content: string }[];
  /** Files now in the runtime directory (path → content). */
  actual: Map<string, string>;
  /** Components of the release. */
  components: string[];
  containers: RunningContainer[];
}): DriftReport {
  const items: DriftItem[] = [];
  const expected = new Map(input.expected.map((f) => [f.path, f.content]));

  for (const [path, content] of expected) {
    const now = input.actual.get(path);
    if (now === undefined) {
      items.push({
        kind: 'file-missing',
        subject: path,
        detail: 'deleted from the runtime directory',
      });
    } else if (sha256(now) !== sha256(content)) {
      items.push({
        kind: 'file-modified',
        subject: path,
        detail: 'edited by hand (raion drift --repair restores it)',
      });
    }
  }
  for (const path of input.actual.keys()) {
    if (!expected.has(path)) {
      items.push({
        kind: 'file-extra',
        subject: path,
        detail: 'not generated by Raion; components may read it',
      });
    }
  }

  // Images as the release's compose file specifies them (pinned by digest).
  const compose = expected.get('compose.yaml');
  const images = new Map<string, string>();
  if (compose) {
    const services = (parse(compose) as { services?: Record<string, { image?: string }> }).services;
    for (const [name, svc] of Object.entries(services ?? {})) {
      if (svc.image) images.set(name, svc.image);
    }
  }

  const byService = new Map(input.containers.map((c) => [c.service, c]));
  for (const component of input.components) {
    const container = byService.get(component);
    if (!container) {
      items.push({ kind: 'component-missing', subject: component, detail: 'no container' });
      continue;
    }
    if (container.state !== 'running') {
      items.push({
        kind: 'component-stopped',
        subject: component,
        detail: `container is ${container.state}`,
      });
    }
    const want = images.get(component);
    if (want && container.image && container.image !== want) {
      items.push({
        kind: 'image-changed',
        subject: component,
        detail: `runs ${container.image}, the release specifies ${want}`,
      });
    }
  }
  for (const c of input.containers) {
    if (!input.components.includes(c.service)) {
      items.push({
        kind: 'component-extra',
        subject: c.service,
        detail: 'a container in the stack that the release does not define',
      });
    }
  }
  return { release: input.release, items };
}
